site_name: meutudo Awesome Data
site_url: 'https://mt-awesome-data.app.com/'
repo_url: https://github.com/meutudo/mt-awesome-data
repo_name: mt-awesome-data
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
nav:
  - Home: index.md
  - Recursos:
      - Ferramentas: recursos/ferramentas.md
      - Bibliotecas: recursos/bibliotecas.md
  - Contribuindo: contribuindo.md
  - Sobre: sobre.md
