site_name: MT Awesome Data
site_url: https://meutudo.github.io/mt-awesome-data/
repo_url: https://github.com/meutudo/mt-awesome-data
repo_name: GitHub
theme:
  name: material
  palette:
    - scheme: default
      primary: '#EE008E'
      accent: '#EE008E'
      toggle:
        icon: material/weather-night
        name: Mudar para o modo escuro
    - scheme: slate
      primary: '#EE008E'
      accent: '#EE008E'
      toggle:
        icon: material/weather-sunny
        name: Mudar para o modo claro
nav:
  - Home: index.md
  - Recursos:
      - Bibliotecas: recursos/bibliotecas.md
      - FAQ: recursos/faq.md
      - Ferramentas: recursos/ferramentas.md
  - Processos Operacionais:
      - Pull Request: processos-operacionais/pull-request.md
  - Contribuindo: contribuindo.md
  - Sobre: sobre.md
# features:
#   - navigation.sections
#   - navigation.top
plugins:
  - search
  - awesome-pages
  # - link-checker
