site_name: MT Awesome Data
site_url: https://meutudo.github.io/mt-awesome-data/
repo_url: https://github.com/meutudo/mt-awesome-data
repo_name: GitHub
theme:
  name: material
  logo: assets/logo-meutudo.png
  # favicon: assets/favicon.ico
  palette:
    primary: indigo
    accent: indigo
nav:
  - Home: index.md
  - Recursos:
      - FAQ: recursos/faq.md
      - Ferramentas: recursos/ferramentas.md
      - Bibliotecas: recursos/bibliotecas.md
  - Contribuindo: contribuindo.md
  - Sobre: sobre.md
